# Generated by Django 5.0.1 on 2024-03-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
